security: fix permissions and SELinux contexts of all repo files
This will fixup all files in /etc/yum.repos.d/ to be root-owned and have the correct SELinux labels

View them with

```
ls -Z /etc/yum.repos.d/
```

diff --git a/copr b/copr
--- a/copr
+++ b/copr
@@ -134,3 +134,12 @@ elif [[ "$1" == "enable" ]]; then
 elif [[ "$1" == "-h" || "$1" == "--h" || "$1" == "-help" || "$1" == "--help" || "$1" == "help" ]]; then
  echo "$helptext"
 fi
+
+##### SECURE REPO FILES #####
+# changing unix permissions to make them root-owned and read-only by world
+# chang SELinux labels to "system_u:object_r:system_conf_t:s0" like the default Fedora repos
+
+echo "Securing the repo files against manipulation. Please enter your password one last time."
+pkexec chown root:root /etc/yum.repos.d/* &&\
+pkexec chmod 744 /etc/yum.repos.d/* || { echo "Failed to secure the repo files!"; exit 1; }
+pkexec chcon -R system_u:object_r:system_conf_t:s0 /etc/yum.repos.d/
