secure the repo files
just added it at a bunch of locations. A more intelligent function is appreciated

diff --git a/copr b/copr
--- a/copr
+++ b/copr
@@ -58,10 +58,23 @@ For help, write me here: https://discussion.fedoraproject.org/u/boredsquirrel/
 EOF
 )
 
-# Main loop
+##### SECURE REPO FILES #####
+# changing unix permissions to make them root-owned and read-only by world
+# chang SELinux labels to "system_u:object_r:system_conf_t:s0" like the default Fedora repos
 
-# TODO
-# detect existing file, change 0 to 1
+secure-files=$(
+        echo "Securing the repo files against manipulation. Please enter your password one last time."
+        pkexec sh -c "
+        chown root:root /etc/yum.repos.d/* && \
+        chmod 744 /etc/yum.repos.d/* && \
+        chcon -R system_u:object_r:system_conf_t:s0 /etc/yum.repos.d/
+        " || {
+                echo "Failed to secure the repo files!"
+                exit 1
+        }
+)
+
+# Main loop
 
 if [[ "$1" == "enable" ]]; then
         while true; do
@@ -76,6 +89,7 @@ if [[ "$1" == "enable" ]]; then
                                 # download the repofile
                                 echo "$author/$reponame -> $releasever"
                                 curl -fsSL "https://copr.fedorainfracloud.org/coprs/$author/$reponame/repo/fedora-$releasever/$author-$reponame-fedora.repo" | pkexec tee "$repofile" >/dev/null
+                                secure-files
                         fi
                         ;;
                 *)
@@ -87,12 +101,14 @@ if [[ "$1" == "enable" ]]; then
 
 # disable a repo
 elif [[ "$1" == "disable" ]]; then
+        secure-files
         sed 's/enabled=1/enabled=0/g' "$repofile" >/dev/null &&
                 echo "Repository "$author"/"$reponame" disabled." ||
                 echo "Already disabled or repo not found."
 
 # remove the named repo
 elif [[ "$1" == "remove" ]]; then
+        secure-files
         # backup the repofile and change owner to user
         mkdir ~/COPR
 
@@ -139,17 +155,3 @@ elif [[ "$1" == "search" ]]; then
 elif [[ "$1" == "-h" || "$1" == "--h" || "$1" == "-help" || "$1" == "--help" || "$1" == "help" ]]; then
         echo "$helptext"
 fi
-
-##### SECURE REPO FILES #####
-# changing unix permissions to make them root-owned and read-only by world
-# chang SELinux labels to "system_u:object_r:system_conf_t:s0" like the default Fedora repos
-
-echo "Securing the repo files against manipulation. Please enter your password one last time."
-pkexec sh -c "
-    chown root:root /etc/yum.repos.d/* && \
-    chmod 744 /etc/yum.repos.d/* && \
-    chcon -R system_u:object_r:system_conf_t:s0 /etc/yum.repos.d/
-" || {
-        echo "Failed to secure the repo files!"
-        exit 1
-}
