big fixes
#9

diff --git a/copr b/copr
--- a/copr
+++ b/copr
@@ -1,15 +1,15 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
 # assign variables for author, reponame and releaseversion
-author="$(echo $2 | cut -d '/' -f1)"
-reponame="$(echo $2 | cut -d '/' -f2)"
+author="$(echo "$2" | cut -d '/' -f1)"
+reponame="$(echo "$2" | cut -d '/' -f2)"
 releasever="$(rpm -E %fedora)"
 repofile="/etc/yum.repos.d/_copr_$author-$reponame.repo"
-repofilebak="~/COPR/_copr_$author-$reponame.repo"
-
+repofilebak="$HOME/COPR/_copr_$author-$reponame.repo"
 
 # The original COPR warning message
-question=$(cat <<EOF
+question=$(
+        cat <<EOF
 Enabling a Copr repository. Please note that this repository is not part
 of the main distribution, and quality may vary.
 
@@ -26,7 +26,8 @@ EOF
 )
 
 # the helptext
-helptext=$(cat << EOF
+helptext=$(
+        cat <<EOF
 
 ====== Experimental COPR Command in non-DNF Fedora Distributions ======
 
@@ -63,84 +64,92 @@ EOF
 # detect existing file, change 0 to 1
 
 if [[ "$1" == "enable" ]]; then
- while true; do
-     read -p "$question" yn
-     case $yn in
-         [Yy]* )
-            # test if the repo file already exists
-            if [[ -e "$repofile" ]]; then
-              # set the repo to active
-              sed 's/enabled=0/enabled=1/g' $repofile > /dev/null && echo "Repository $author/$reponame enabled" || echo "Already enabled or repo not found."
-            else
-            # download the repofile
-              echo "$author/$reponame -> $releasever"
-              curl -fsSL https://copr.fedorainfracloud.org/coprs/$author/$reponame/repo/fedora-$releasever/$author-$reponame-fedora-.repo | pkexec tee $repofile && break;;
-         * ) echo "Unknown option, exiting." && break;;
-     esac
-  done
+        while true; do
+                read -rp "$question" yn
+                case $yn in
+                [Yy]*)
+                        # test if the repo file already exists
+                        if [[ -e "$repofile" ]]; then
+                                # set the repo to active
+                                sed -i 's/enabled=0/enabled=1/g' "$repofile" && echo "Repository $author/$reponame enabled" || echo "Already enabled or repo not found."
+                        else
+                                # download the repofile
+                                echo "$author/$reponame -> $releasever"
+                                curl -fsSL "https://copr.fedorainfracloud.org/coprs/$author/$reponame/repo/fedora-$releasever/$author-$reponame-fedora.repo" | pkexec tee "$repofile" >/dev/null
+                        fi
+                        ;;
+                *)
+                        echo "Unknown option, exiting."
+                        break
+                        ;;
+                esac
+        done
 
 # disable a repo
 elif [[ "$1" == "disable" ]]; then
-  sed 's/enabled=1/enabled=0/g' $repofile > /dev/null \
-  && echo "Repository $author/$reponame disabled." \
-  || echo "Already disabled or repo not found."
+        sed 's/enabled=1/enabled=0/g' "$repofile" >/dev/null &&
+                echo "Repository "$author"/"$reponame" disabled." ||
+                echo "Already disabled or repo not found."
 
 # remove the named repo
 elif [[ "$1" == "remove" ]]; then
-  # backup the repofile and change owner to user
-  mkdir ~/COPR
+        # backup the repofile and change owner to user
+        mkdir ~/COPR
 
-  if [[ -e "$repofile" ]]; then
-      # Backup existing repo file and set ownership to the user
-      pkexec cp $repofile $repofilebak \
-      && pkexec chown $USER "$backup_file" \
-      && echo "Backup created in your home folder."
+        if [[ -e "$repofile" ]]; then
+                # Backup existing repo file and set ownership to the user
+                pkexec cp "$repofile" "$repofilebak" &&
+                        pkexec chown "$USER" "$backup_file" &&
+                        echo "Backup created in your home folder."
 
-      # Remove the repo file
-      pkexec rm $repofile \
-      && echo "COPR Repository $author/$reponame removed." \
-      || echo "ERROR removing COPR repository."
-  else
-      # search for the reponame
-      echo "Repo with name $author/$reponame not found, trying a search..."
+                # Remove the repo file
+                pkexec rm "$repofile" &&
+                        echo 'COPR Repository "$author"/"$reponame" removed.' ||
+                        echo "ERROR removing COPR repository."
+        else
+                # search for the reponame
+                echo 'Repo with name "$author"/"$reponame"" not found, trying a search...'
 
-      result=$(grep -ril --include='*.repo' "$reponame" /etc/yum.repos.d/)
-      # if not found, exit
-      if [[ -z "$result" ]]; then
-          echo "No repositories containing '$reponame' were found." \
-          && break
-      else
-          # if found, make sure it is the right one
-          read -rp "Repo '$result' was found. Do you want to backup and remove this repo? (Y/N) " answer
-          if [[ "${answer,,}" == "y" ]]; then
-              pkexec cp "$result" "$backup_file" \
-              && pkexec chown "$(whoami)" "$backup_file" \
-              && pkexec rm "$result" \
-              && echo "COPR Repository '$reponame' removed." \
-              || echo "ERROR removing COPR repository."
-          fi
-      fi
-  fi
+                result=$(grep -ril --include='*.repo' "$reponame" /etc/yum.repos.d/)
+                # if not found, exit
+                if [[ -z "$result" ]]; then
+                        echo 'No repositories containing "$reponame" were found.'
+                        exit 1
+                else
+                        # if found, make sure it is the right one
+                        read -rp 'Repo "$result" was found. Do you want to backup and remove this repo? (Y/N) ' answer
+                        if [[ "${answer,,}" == "y" ]]; then
+                                pkexec cp "$result" "$backup_file" &&
+                                        pkexec chown "$(whoami)" "$backup_file" &&
+                                        pkexec rm "$result" || #               && echo 'COPR Repository "$reponame" removed.' \
+                                        echo "ERROR removing COPR repository."
+                        fi
+                fi
+        fi
 
 # list all installed COPR repositories
 elif [[ "$1" == "list" ]]; then
- find /etc/yum.repos.d/ -type f -name '_copr*' -exec basename {} \; | sed 's/_copr_//; s/\.repo$//'
+        find /etc/yum.repos.d/ -type f -name '_copr*' -exec basename {} \; | sed 's/_copr_//; s/\.repo$//'
 
 # search, this is just implemented through the browser (hey, pip does the same!)
 elif [[ "$1" == "search" ]]; then
- xdg-open "https://copr.fedorainfracloud.org/coprs/fulltext/?fulltext=$2"
+        xdg-open "https://copr.fedorainfracloud.org/coprs/fulltext/?fulltext=$2"
 
 # display the helptext
 elif [[ "$1" == "-h" || "$1" == "--h" || "$1" == "-help" || "$1" == "--help" || "$1" == "help" ]]; then
- echo "$helptext"
+        echo "$helptext"
 fi
-
 
 ##### SECURE REPO FILES #####
 # changing unix permissions to make them root-owned and read-only by world
 # chang SELinux labels to "system_u:object_r:system_conf_t:s0" like the default Fedora repos
 
 echo "Securing the repo files against manipulation. Please enter your password one last time."
-pkexec sh -c "chown root:root /etc/yum.repos.d/* && \
-               chmod 744 /etc/yum.repos.d/* && \
-               chcon -R system_u:object_r:system_conf_t:s0 /etc/yum.repos.d/" || { echo "Failed to secure the repo files!"; exit 1; }
+pkexec sh -c "
+    chown root:root /etc/yum.repos.d/* && \
+    chmod 744 /etc/yum.repos.d/* && \
+    chcon -R system_u:object_r:system_conf_t:s0 /etc/yum.repos.d/
+" || {
+        echo "Failed to secure the repo files!"
+        exit 1
+}
